export const AUTH_COPY = {
  title: "Continue with OTP",
  subtitle:
    "Enter your phone number and we’ll send a code. If it’s your first time, we’ll ask for your name and email after the OTP is verified.",
  submit: "Verify OTP",
  createAccount: "Create account",
  submitting: "Verifying…",
  sendOtp: "Send OTP",
  fields: {
    name: { label: "Your name", hint: "Needed the first time you sign up." },
    countryCode: { label: "Code" },
    phone: { label: "Phone", placeholder: "Phone number" },
    email: {
      label: "Email",
      hint: "Optional — we use it for order receipts.",
    },
    otp: { label: "OTP" },
    password: { label: "Password" },
    newPassword: { label: "Choose a password", hint: "At least 8 characters." },
  },
  password: {
    title: "Log in",
    subtitle: "Use your phone number and password.",
    submit: "Log in",
    submitting: "Logging in…",
    forgot: "Forgot password?",
    useOtp: "Log in with OTP instead",
    usePassword: "Log in with password instead",
    newHere: "New to Keyafe?",
    createLink: "Create an account",
  },
  register: {
    title: "Create your account",
    subtitle: "Save addresses and track your orders.",
    emailHint: "Optional — for order receipts and resetting your password.",
    submit: "Create account",
    submitting: "Creating account…",
    haveAccount: "Already have an account?",
    loginLink: "Log in",
  },
  forgot: {
    title: "Reset your password",
    subtitle: "We’ll email a reset link to the address saved on your account.",
    submit: "Send reset link",
    submitting: "Sending…",
    noEmail: "No email on your account? Log in with OTP, or call us on +91 93300 48665.",
    back: "Back to log in",
  },
  changePassword: {
    setTitle: "Set a password",
    changeTitle: "Change password",
    setDescription: "Log in next time with your phone number and this password.",
    changeDescription: "You’ll stay logged in here. Other devices will be logged out.",
    current: "Current password",
    repeat: "Repeat new password",
    mismatch: "Passwords don’t match",
    submit: "Save password",
    submitting: "Saving…",
    done: "Password saved.",
  },
  reset: {
    title: "Choose a new password",
    subtitle: "This link works once and expires 30 minutes after it was sent.",
    missingToken:
      "This link is missing its reset code. Request a new one from Log in → Forgot password.",
    submit: "Save new password",
    submitting: "Saving…",
  },
  headerButton: "Log in",
  menu: {
    myOrders: "My orders",
    savedAddresses: "Saved addresses",
    setPassword: "Set a password",
    changePassword: "Change password",
    logout: "Log out",
  },
} as const;
